backend/models/Partner.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "node".
 *
 * @property integer $id
 * @property string $title
 * @property string $summary
 * @property string $description
 * @property string $other
 * @property string $image
 * @property string $video
 * @property string $price
 * @property string $link
 * @property string $file
 * @property integer $setting
 * @property string $digit1
 * @property string $digit2
 * @property string $digit3
 * @property string $digit4
 * @property string $digit5
 * @property string $field1
 * @property string $field2
 * @property string $field3
 * @property string $inner
 * @property string $sub_title
 * @property string $text1
 * @property string $text2
 * @property string $text3
 * @property string $text4
 * @property string $text5
 * @property integer $started_at
 * @property integer $ended_at
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $status
 * @property integer $menu
 * @property string $type
 * @property string $slug
 *
 * @property NodeImage[] $nodeImages
 */
class Partner extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $img;
    public static function tableName()
    {
        return 'node';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['summary', 'description', 'other', 'text1', 'text2', 'text3', 'text4', 'text5'], 'string'],
            [['price', 'digit1', 'digit2', 'digit3', 'digit4', 'digit5'], 'number'],
            [['setting', 'started_at', 'ended_at', 'created_at', 'updated_at', 'created_by', 'updated_by', 'status', 'menu'], 'integer'],
            [['title', 'image', 'video', 'link', 'file', 'field1', 'field2', 'field3', 'inner', 'sub_title', 'type', 'slug','category','tags'], 'string', 'max' => 255],
            [['title'],'required'],
            ['img', 'image','minWidth' => 235, 'minHeight' => 90,'maxWidth' => 236, 'maxHeight' => 90, 'extensions' => 'png, jpg'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Name',
            'summary' => 'Summary',
            'description' => 'Description',
            'other' => 'Designation',
            'img' => 'Image',
            'video' => 'Video',
            'price' => 'Price',
            'link' => 'Link',
            'file' => 'File',
            'setting' => 'Setting',
            'digit1' => 'Digit1',
            'digit2' => 'Digit2',
            'digit3' => 'Digit3',
            'digit4' => 'Digit4',
            'digit5' => 'Digit5',
            'field1' => 'Field1',
            'field2' => 'Field2',
            'field3' => 'Field3',
            'inner' => 'Inner',
            'sub_title' => 'Sub_title',
            'text1' => 'Designation',
            'text2' => 'Company',
            'text3' => 'Text3',
            'text4' => 'Text4',
            'text5' => 'Text5',
            'started_at' => 'Started At',
            'ended_at' => 'Ended At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
            'menu' => 'Menu',
            'type' => 'Type',
            'slug' => 'Slug',
        ];
    }
    public function behaviors()
    {
      return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
            ],
            [
                'class' => 'yii\behaviors\SluggableBehavior',
                'attribute' => 'title',
                'ensureUnique'=>true,
                // 'slugAttribute' => 'slug',
            ],
            [
                'class' => 'yii\behaviors\BlameableBehavior',
            ]
      ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNodeImages()
    {
        return $this->hasMany(NodeImage::className(), ['nid' => 'id']);
    }
    public function getCreatedBy()
    {
        return $this->hasOne('common\models\User', ['id' => 'created_by']);
    }
    public function getUpdatedBy()
    {
        return $this->hasOne('common\models\User', ['id' => 'updated_by']);
    }
    /**
     * Returns content and replace widgets short codes
     *
     * Widget short code example: [[\app\widgets\SomeWidget:method]]
     *
     * @return string
     */
    public function getContent()
    {
        $content = preg_replace_callback('/\[\[([^(\[\[)]+:[^(\[\[)]+)\]\]/is', [$this, 'replace'], $this->description);
        return $content;
    }
    /**
     * Replaces widget short code on appropriate widget
     *
     * @param $data
     *
     * @return string
     */
    private function replace($data)
    {
        $widget = explode(':', $data[1]);
        if (class_exists($class = $widget[0]) && method_exists($class, $method = $widget[1])) {
            return call_user_func([$class, $method]);
        }
        return '';
    }
    public function getAvatarImage(){
        return yii\helpers\Html::img(Yii::getAlias('@url').'/partners/'.$this->image);
    }
    public function getDes()
    {
        if(isset($this->text1) && $this->text2 != NULL)
        return ucwords(preg_replace('/\s+/', '@',$this->text1.' '.$this->text2));
    }
   public function getMainTitle()
    {
        return preg_replace('/\s+/', ' ',$this->title.' '.$this->sub_title);
    }
}

frontend/views/widgets/widget--awards.php
<?php
use yii\helpers\Html;
use common\helpers\Url;
?>
<section class="awards-area">
<div class="container">
<div class="row">
<div class="col-lg-4 col-sm-12 our-achievements-text" data-scrollreveal="enter top over 2s after 0.5s">
<h2><span>Our</span>Achievements and awards</h2>
<?=\yii\helpers\StringHelper::truncate($model->description,170,'','UTF-8',true)?>
<a href="<?=Url::node('/node/4')?>">View More <i class="fas fa-arrow-circle-right"></i></a>
</div>
<div class="col-lg-8 col-sm-12 owl-carousel-1 owl-slides no-padding" data-scrollreveal="enter top over 4s after 1s">
<?php foreach ($model->nodeImages as $img):?>	
<div class="item active">
<div class="row">
<div class="col-sm-12 awards-details">
<figure><img src="<?=Yii::getAlias('@url').'/nodeimages/'.$img->node_image?>" alt="<?=$img->node_image_title?>"></figure>
<h2><?=$img->node_image_title?></h2>
<h3>Achieved on : <?=date('d-m-Y',$img->date)?></h3>
</div>
</div>
</div>
<?php endforeach;?>
</div>
</div>
</div>
</section>


               

              

            

frontend/views/widgets/widget--banners.php
<?php
use yii\helpers\Html;
$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@webroot/webassets');
$first = true;
?>
<div class="carousel-inner">
<div class="slider-overlay">
<?php foreach ($models as $model):?>
<?php if($first): $first = false; ?>
<div class="carousel-item active">
<a href="<?=$model->link?>">
<img src="<?=Yii::getAlias('@url').'/banners/'.$model->image?>" alt="<?=$model->title?>">
</a>
</div>
<?php else: ?>
<div class="carousel-item">
<a href="<?=$model->link?>">
<img src="<?=Yii::getAlias('@url').'/banners/'.$model->image?>" alt="<?=$model->title?>">
</a>
</div>
<?php endif; ?>
<?php endforeach;?>
</div>
<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
<img src="<?=$directoryAsset ?>/images/arrow-left.png" alt="left">
</a>
<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
<img src="<?=$directoryAsset ?>/images/arrow-right.png" alt="right">
</a>
</div>

               

              

            

frontend/views/widgets/widget--brands.php
<?php
use yii\helpers\Html;
?>
<section class="clients-area">
<div class="container">
<div class="row">
<div class="col-sm-12 clients-head">
<h2><span>Our</span> Brands</h2>
</div>
<div class="col-sm-12 owl-carousel-3 owl-slides no-padding">
<?php foreach ($model->nodeImages as $img):?>
<div class="item active">
<div class="row">
<div class="col-sm-12">
<figure><img src="<?=Yii::getAlias('@url').'/nodeimages/'.$img->node_image?>" alt="<?=$img->node_image_title?>"></figure>
</div>
</div>
</div>
<?php endforeach;?>
</div>
</div>
</div>
</section>


               

              

            

frontend/views/widgets/widget--featured.php
<?php
use yii\helpers\Html;
$f1 = true;
$f2 = true;
?>
<div class="row">
<nav class="col-lg-3 col-xs-12 mainMenu">
<label for="toggleMenu" class="menuTitle" onclick="">&nbsp;</label>
<input type="checkbox" id="toggleMenu" />
<ul>
<div data-scrollreveal="enter left over 2s after 0.5s">
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
<?php foreach ($models as $model):?>
<?php if($f1): $f1 = false; ?>
<a class="nav-link active" id="v-pills-<?=$model->id?>-tab" data-toggle="pill" href="#v-pills-<?=$model->id?>" role="tab" aria-controls="v-pills-home" aria-selected="true"><?=$model->title?></a>
 <?php else: ?>
 <a class="nav-link" id="v-pills-<?=$model->id?>-tab" data-toggle="pill" href="#v-pills-<?=$model->id?>" role="tab" aria-controls="v-pills-home" aria-selected="true"><?=$model->title?></a>
 <?php endif;endforeach;?>
</div>
</div>
</ul>
</nav>
<div class="col-lg-9 col-xs-12" data-scrollreveal="enter right over 2s after 0.5s">
<div class="tab-content" id="v-pills-tabContent">
<?php foreach ($models as $model):?>
<?php if($f2): $f2 = false; ?>
<div class="tab-pane fade show active" id="v-pills-<?=$model->id?>" role="tabpanel" aria-labelledby="v-pills-a-tab">
<div class="container">
<div class="row">
<div class="col-sm-12 features-details">
<img src="<?=Yii::$app->imagemanager->getImagePath($model->icon)?>" alt="icon">
<h4><?=$model->title?></h4>
<?=$model->description?>
<h5>Other details</h5>
<?=$model->other?>
</div>
</div>
</div>
</div>
 <?php else: ?>
<div class="tab-pane fade" id="v-pills-<?=$model->id?>" role="tabpanel" aria-labelledby="v-pills-b-tab">
<div class="container">
<div class="row">
<div class="col-sm-12 features-details">
<img src="<?=Yii::$app->imagemanager->getImagePath($model->icon)?>" alt="icon">
<h4><?=$model->title?></h4>
<?=$model->description?>
<h5>Other details</h5>
<?=$model->other?>
</div>
</div>
</div>
</div>
<?php endif;endforeach;?>
</div>
</div>
</div>

               

              

            

frontend/views/widgets/widget--partners.php
<?php
use yii\helpers\Html;
?>
<div class="col-sm-12 owl-3 owl-theme owl-slides" data-scrollreveal="enter top over 2s after 0.5s">
<?php foreach ($models as $model):?>  
<div class="item">
<div class="row">
<div class="col-sm-12 profile">
<img src="<?=Yii::getAlias('@url').'/partners/'.$model->image?>" alt="<?=$model->title?>">
</div>
</div>
</div>
<?php endforeach;?>
</div>


               

              

            

frontend/views/widgets/widget--product-links.php
<?php
use yii\helpers\Html;
use common\helpers\Url;
?>
<ul class="list-styled">
<?php foreach ($models as $model):?>
<li><a href="<?=Url::node('/node/'.$model->id)?>"><?=$model->title?></a></li>
<?php endforeach;?>
</ul>


               

              

            

frontend/views/widgets/widget--products.php
<?php
use yii\helpers\Html;
use common\helpers\Url;
?>
<section class="our-product-area">
<div class="container">
<div class="row">
<div class="col-sm-12 products-head" data-scrollreveal="enter bottom over 2s after 0.5s">
<h2><span>Our</span> Products</h2>
</div>
<div class="col-sm-12 owl-carousel-2 owl-slides no-padding" data-scrollreveal="enter bottom over 2s after 1s">
<?php foreach ($models as $model):?>
<div class="item active">
<div class="row">
<div class="col-sm-12 product-details">
<figure><a href="#"><img src="<?=Yii::getAlias('@url').'/products/'.$model->image?>" alt="<?=$model->title?>"></a></figure>
<div class="product-title">
<h4><?=$model->title?></h4>
<a href="<?=Url::node('/node/'.$model->id)?>">Read More <i class="fas fa-arrow-circle-right"></i></a>
</div>
</div>
</div>
</div>
<?php endforeach;?>
</div>
</div>
</div>
</section>


               

              

            

frontend/views/widgets/widget--promotional.php
<?php
use yii\helpers\Html;
$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@webroot/webassets');
$first = true;
?>
<div class="col-sm-12 app-screen-head">
<img class="dots-head" src="<?=$directoryAsset ?>/images/head-dots.png" alt="dots">
<img src="<?=Yii::$app->imagemanager->getImagePath(Yii::$app->settings->img('logo-body'),275,102)?>" alt="logo">
<p><?=$model->summary?></p>
</div>
<div class="col-sm-12 mobile-splash-screens" data-scrollreveal="enter top over 2s after 0.5s">
<div class="mobile-slider2">
<div id="carouselExampleIndicators2" class="carousel slide carousel-fade" data-ride="carousel">
<div class="carousel-inner d-none d-xl-block d-md-block d-lg-block">
<?php foreach ($model->nodeImages as $image):?>
<?php if($first): $first = false; ?>
<div class="carousel-item active">
<img src="<?=Yii::getAlias('@url/nodeimages/').$image->node_image?>" alt="<?=$image->node_image_title?>">
</div>
<?php else: ?>
<div class="carousel-item">
<img src="<?=Yii::getAlias('@url/nodeimages/').$image->node_image?>" alt="<?=$image->node_image_title?>"></div>
<?php endif; ?>
<?php endforeach; ?>
</div>
<div class="carousel-inner d-md-none d-lg-none d-sm-block">
<div class="col-sm-12 carousel-item active">
<img src="<?=Yii::$app->imagemanager->getImagePath(7,354,453)?>" alt="slides">
</div>
<div class="col-sm-12 carousel-item">
<img src="<?=Yii::$app->imagemanager->getImagePath(8,354,453)?>" alt="slides">
</div>
</div>
</div>
</div>
</div>

frontend/views/widgets/widget--testimonial.php
<?php
use yii\helpers\Html;
?>
<div class="col-sm-12 owl-2 owl-theme owl-slides" data-scrollreveal="enter top over 2s after 1s">
<?php foreach ($models as $model):?>  
<div class="item">
<div class="row">
<div class="col-sm-12 client-area">
<div class="client-details">
<div class="row justify-content-center">
<div class="col-sm-2 profile-pic offset-3">
<img src="<?=Yii::getAlias('@url').'/testimonials/'.$model->image?>" alt="profile" class="rounded-circle">
</div>
<div class="col-sm-7 profile-name no-padding">
<h5><?=$model->title?></h4>
<h6><?=$model->des?></h6>
</div>
</div>
<div class="row">
<div class="col-sm-12 profile-disc">
<p><?=\yii\helpers\StringHelper::truncate($model->description,140,'...','UTF-8',false)?>
</div>
</div>
</div>
</div>
</div>
</div>
<?php endforeach;?>
</div>


               

              

            